### ISSUE TITLE
How to pass a callback function to "OnCreateWorker" method?

### ISSUE THREAD

**Issue by PratikDarak** [josdejong/workerpool#348] opened 2022-06-29 10:59 UTC
Hi,

I am working on a scenario where I want to execute a callback function each time a new worker is created. Can you please share an example of how it can be achieved?

To give a context in little more detail, I am using Go + WASM + Workerpool setup where I am offloading the WASM tasks to workerpool so that it doesn't occupy my main thread. In this setup, I want to execute `go.run` command with the WASM instance in each worker so that each worker can execute the WASM functions.

It will be really helpful if you can share an example of how can I pass the callback function to `onCreateWorker` method. Thank you.

**Comment by josdejong** [comment] 2022-06-29 11:10
Closing this issue as a duplicate of #349

**Closed by josdejong** 2022-06-29 11:10 UTC
