### ISSUE TITLE
Using proxy increases memory usage, eventually causing crash

### ISSUE THREAD

**Issue by ehsanghorbani190** [josdejong/workerpool#471] opened 2024-10-07 17:46 UTC
Hi! I have a dedicated worker file which contains a function that renders a page and saves it to the file.
I have a function like this:
```js
const pool = workerpool.pool(path.resolve(__dirname, "worker.js"), {
  maxWorkers: 20,
});

function renderAndSave(options, onFinish) {
  const token = getToken();

  return pool
    .proxy()
    .then(({ generate }) => generate(options, token).timeout(50000))
    .then(({ code, start_time, log_data }) => {
      if (code === 429) {
        disableToken(token);
        renderAndSave(options, onFinish);
      } else if (code === 401) {
        deleteToken(token);
        renderAndSave(options, onFinish);
      } else if (typeof onFinish === "function") onFinish(code, log_data);
      
    })
    .catch((e) => {
      throw e;
    });
}
```
I call this function on a large scale, via a `forEach` on an array with a length of say 7000 items. The caller function looks like this:
```js
function savePages(){
 const a = [...];
 const b = [...];
a.forEach(ai => {
 b.forEach(bi => {
  renderAndSave({...},...);
  });
 });
}
```
After calling this function, the pool starts to save pages as expected, but a problem arises as the time pass. The process memory of the main program rises exponentially, causing the program to be killed after some time.
Am i using the worker pool wrong in a loop? 

}

**Comment by josdejong** [comment] 2024-10-09 09:01
You code looks fine at first sight. 

To figure out if the growing memory usage is caused by something in combination with `workerpool` or just by somthing in your own code, as a test I would try to run your program in the main thread, without `workerpool`.

**Comment by ehsanghorbani190** [comment] 2024-10-11 07:21
@josdejong 
I haven't tested it yet, but I will. I thought that maybe I'm spawning too many tasks at once and waiting tasks cause memory usage. But if I call the caller function 300 times, for example, the memory used by the main process goes up and stays there even when all pages are generated. Not that it goes up way high, but it goes up for 300 MB for example and stays there, not going down)

**Comment by josdejong** [comment] 2024-10-23 06:26
Can we close this issue @ehsanghorbani190? It's not actionable for me.

**Comment by ehsanghorbani190** [comment] 2024-10-26 18:02
@josdejong yes, I will try the solution after my current task in work.

**Closed** 2024-10-26 18:02 UTC
Labels: question
