### ISSUE TITLE
"Worker is terminated" on crash

### ISSUE THREAD

**Issue by mroohian** [josdejong/workerpool#155] opened 2020-05-27 17:50 UTC
Hi,

In my worker process I call `dlopen()` to load some libraries and call some of their methods that often crash with `SIGILL` or `SIGSEGV`. I expect the worker process to be immediately recreated with minWorkers and maxWorkers both set to one.

Sometimes when the worker process crashes, the very next calls throws a **"Worker is terminated"** error and then recreates the worker. Am I missing something or is there a way to check the worker terminated flag and force it to recreate the worker.

Thank you for your time.

**Comment by josdejong** [comment] 2020-05-27 18:29
Thanks for reporting. Sounds like a bug, but we'll have to see. Is there an easy way to reproduce your issue?

**Comment by mroohian** [comment] 2020-05-27 18:53
Thank you for the quick response.

The libraries that I work with connect to some hardware and can often fail if the hardware stops working, therefore it is difficult to simulate the crash by an example. Nevertheless I've tried to reproduce it with this method `void libMethod(void) { asm("ud2"); }` but the onError code in the worker code handles it correctly. My guess is the some crashes are handled correctly and some are for whatever reason not and maybe it depends on how the process is terminated.

As the terminated flag in the worker code is set to true, I'm looking for a possibility to hook into it and recreate the process or at least reset the states and remove the worker from the available workers list. In any case, I am looking for a public API to examine if the worker is terminated and recreate it.

**Comment by josdejong** [comment] 2020-05-27 19:33
There are already some unit tests in place to test crashed workers. Maybe it's as simple as writing a unit test with `minWorkers: 1` and `maxWorkers: 1`, run one crashing task, and then try run something non-crashing after that.

**Comment by mroohian** [comment] 2020-05-27 20:27
Hi again, I created a small test with a normal method and crash method I can see that the crash method handles the error correctly.

https://github.com/mroohian/workerpool_napi_unit_test

**Comment by josdejong** [comment] 2020-05-30 10:54
Ehh, so you mean your test does not reproduce the issue you're encountering? Or does it?

**Comment by mroohian** [comment] 2020-05-31 11:33
Nom the example I provided does not reproduce the error. But the error keeps happening by running the actual hardware code. I've managed to call an empty **wakeUp** function after every hardware call to ensure that the worker is restored in case of crash but still not sure why the certain crashes are not detected by the library and causes "Worker is terminated" error.

**Comment by josdejong** [comment] 2020-06-06 11:57
Hm. Without being able to reproduce I don't know how to figure out the cause of this. Any other ideas?

**Comment by josdejong** [comment] 2020-08-10 15:31
Will close this issue now, please reopen if there is a way to reproduce this issue.

**Closed by josdejong** 2020-08-10 15:31 UTC
