### ISSUE TITLE
npm i workerpool failed

### ISSUE THREAD

**Issue by chengdonglin** [josdejong/workerpool#61] opened 2019-03-12 05:44 UTC
the following error:
```
memory.cpp
  win_delay_load_hook.cc
..\src\memory.cpp(6): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory [E:\electron_project\TMAPConver
tSDK\x64\node_modules\shmmap\build\shmmap.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nvm\v8.11.2\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "E:\\nodejs\\node.exe" "E:\\nvm\\v8.11.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\electron_project\TMAPConvertSDK\x64\node_modules\shmmap
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN x64@1.0.0 No description
npm WARN x64@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: shmmap@0.2.0 (node_modules\shmmap):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: shmmap@0.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by josdejong** [comment] 2019-03-12 19:28
Thanks for reporting @chengdonglin. From the error I understand this is happening in an Electron application, is that correct? How can I reproduce this issue?

**Comment by chengdonglin** [comment] 2019-03-13 00:19
> Thanks for reporting @chengdonglin. From the error I understand this is happening in an Electron application, is that correct? How can I reproduce this issue?

Thanks for reply! I think you can git clone a simple electron from the github, then npm install workerpool under this project, I think can reproduce this issue.

**Comment by chengdonglin** [comment] 2019-03-13 00:24
Thanks for reply. If you want to reproduce this issue, I think you can git clone a simple electron project from github, then npm install workerpool under the project.

发送自 Windows 10 版邮件应用

发件人: Jos de Jong
发送时间: 2019年3月13日 3:28
收件人: josdejong/workerpool
抄送: chengdonglin; Mention
主题: Re: [josdejong/workerpool] npm i workerpool failed (#61)

Thanks for reporting @chengdonglin. From the error I understand this is happening in an Electron application, is that correct? How can I reproduce this issue?

**Comment by josdejong** [comment] 2019-03-14 21:08
I've created an electron app and run the [first example from the docs](https://github.com/josdejong/workerpool#offload-functions-dynamically), that works fine. Can you reproduce it with a plain Electron app?

What I did is:

```
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
$ npm install
$ npm install workerpool
```
Then, in `renderer.js`, put the following code:
```js
// This file is required by the index.html file and will
// be executed in the renderer process for that window.
// All of the Node.js APIs are available in this process.

var workerpool = require('workerpool');
var pool = workerpool.pool();

function add(a, b) {
  return a + b;
}

pool.exec(add, [3, 4])
    .then(function (result) {
      document.write('result: ' + result); // outputs 7
    })
    .catch(function (err) {
      document.write('error: ' + err.toString());
    })
    .then(function () {
      pool.terminate(); // terminate all workers when done
    });
```
After starting the electron app it displays the "result: 7" as expected.

```
$ npm start
```

**Comment by josdejong** [comment] 2019-06-01 06:12
@chengdonglin I will close this issue now because I don't know how to reproduce. If you have more information please let me know.

**Closed by josdejong** 2019-06-01 06:12 UTC
